# Generated by Django 4.2.4 on 2023-08-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0004_auto_20200906_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='JobType',
            field=models.CharField(choices=[('Full-Time', 'full-time'), ('Part-Time', 'part-time'), ('Temporary', 'temporary')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
