# Generated by Django 4.2.4 on 2023-08-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0006_rename_salary_company_salaryfrom_company_salaryto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='salaryterms',
            field=models.CharField(choices=[('month', 'month'), ('week', 'week')], max_length=200, null=True),
        ),
    ]
