# Generated by Django 4.2.4 on 2023-08-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0007_company_salaryterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='experience',
            field=models.CharField(choices=[('Experienced', 'Experienced'), ('Intermediate', 'Intermediate'), ('Trainee', 'Trainee')], max_length=200, null=True),
        ),
    ]
