# Generated by Django 4.2.4 on 2023-08-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0008_alter_company_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
