# Generated by Django 4.2.4 on 2023-08-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0010_applicant_rename_name_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
