# Generated by Django 4.2.4 on 2023-08-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0011_alter_applicant_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='JobType',
        ),
        migrations.AddField(
            model_name='company',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
